### ISSUE TITLE
Wrong documentation in GenPdfInfo

### ISSUE THREAD

**Issue by hegner** [hep-mirrors/hepmc3#1]
The line 
https://github.com/hep-mirrors/hepmc3/blob/bbbff5efce137ed7ac480b58dfa60de93d12b411/include/HepMC3/GenPdfInfo.h#L22
should probably point to
[https://lhapdf.hepforge.org/pdfsets.html](https://lhapdf.hepforge.org/pdfsets.html)
instead

**Comment by veprbl** [comment]
This is just a mirror. Please report upstream https://gitlab.cern.ch/hepmc/HepMC3.
